version: '3'

services:
  sentiment-api:
    build: .
    image: sentiment-analysis-api
    container_name: sentiment-analysis-api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - model-cache:/root/.cache/huggingface  # Persist model downloads
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  model-cache:  # Named volume for model cache